---
title: "Dashboard"
author: "Hieu T. Le"
date: "`r Sys.Date()`"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
library(rstatix)
library(readr)
library(shiny)
library(ggplot2)
library(rstatix)
library(dplyr)
knitr::opts_chunk$set(echo = TRUE)
```

This R Markdown document is made interactive using Shiny. Unlike the more traditional workflow of creating static reports, you can now create documents that allow your readers to change the assumptions underlying your analysis and see the results immediately. 

To learn more, see [Interactive Documents](http://rmarkdown.rstudio.com/authoring_shiny.html).

```{r}
library(shiny)
library(ggplot2)
agedata.csv = read_csv("agedata.csv")

ui = fluidPage(
  titlePanel("Cholesterol Levels Dashboard"),
  sidebarLayout(
    sidebarPanel(
      selectInput("age_group", "Select Age Group:", choices = unique(agedata.csv$`Age group`))
    ),
    mainPanel(
      plotOutput("cholesterol_plot")
    )
  )
)

server = function(input, output) {
  filtered_data = reactive({
    agedata.csv %>% filter(`Age group` == input$age_group)
  })
  output$cholesterol_plot = renderPlot({
    age_group_colors = c("18-19" = "red", "20-24" = "blue", "25-29" = "green", "30-34" = "orange", "35-39" = "purple", "40-44" = "brown", "45-49" = "black", "50-54" = "navy", "55-59" = "gray", "60-64" = "white", "65-69" = "violet", "70-74" = "gold", "75-79" = "yellow", "80-84" = "")
    ggplot(filtered_data(), aes(x = Country, y = `Mean total cholesterol (mmol/L)`, fill = `Age group`)) +
      geom_bar(stat = "identity", position = "dodge") +
      labs(title = paste("Cholesterol levels for", input$age_group, "Age group"),
           x = "Country", y = "Mean Cholesterol Levels") +
      scale_fill_manual(values = age_group_colors) +
      theme(axis.text.x = element_text(angle = 45, hjust = 1))
  })
}
shinyApp(ui, server)

```




